FROM node:18-slim

ENV NODE_ENV development

ARG DB_ADDRESS
ARG CORS_ORIGIN

ENV DB_ADDRESS $DB_ADDRESS
ENV CORS_ORIGIN $CORS_ORIGIN

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm i

COPY . .

CMD [ "npm", "run", "dev" ]

EXPOSE 3000
