
@startuml

!include <c4/C4_Container.puml>
!include <tupadr3/devicons/react>
!include <tupadr3/devicons/docker.puml>
!include <tupadr3/font-awesome/users>
'!include <cloudogu/tools/docker>
'allowmixing

skinparam defaultFontName SansSerif
skinparam defaultFontSize 12
skinparam HyperlinkColor #335DA5
skinparam HyperlinkUnderline false
skinparam wrapWidth 200

title \n= Диаграмма микрофронтендов Mesto\n\n\n

HIDE_STEREOTYPE()

AddElementTag("users", $bgColor="transparent", $fontColor="#335DA5", $borderThickness="0", )
AddElementTag("mf-host", $sprite="react", $shadowing="true", $bgColor="#335DA5", $shape=EightSidedShape(), $legendText="host")
AddElementTag("mf-remote", $sprite="react", $shadowing="true", $legendText="remote")

Person(user, "User", $sprite="users", $tags="users")

'SetPropertyHeader("lib","version")
WithoutPropertyHeader()
AddProperty("react", "^17.0.2")
AddProperty("react-dom", "^17.0.2")
AddProperty("react-router-dom", "^5.2.0")

System_Boundary(mesto_system, "[[c4_container.puml MESTO System »»]]") {

Container(host, "Host", "React JS", "Host App", $tags="mf-host")
Container(auth, "Auth", "React JS", "Auth App", $tags="mf-remote")
Container(profile, "Profile", "React JS", "Profile App", $tags="mf-remote")
Container(card, "Card", "React JS", "Card App", $tags="mf-remote")
Container(marginals, "Marginals", "React JS", "Marginals App", $tags="mf-remote")
Container(popups, "Popups", "React JS", "Popups App", $tags="mf-remote")

}

Rel(user, host, "uses :3100", "https")

Rel_Back(host, auth, "consumes :3002", "http")
Rel_Back(host, profile, "consumes :3003", "http")
Rel_Back(host, card, "consumes :3004", "http")
Rel_Back(host, marginals, "consumes :3006", "http")
Rel_Back(host, popups, "consumes :3005", "http")

SHOW_FLOATING_LEGEND()

footer drawn with PlantUML v. %version() and C4-PlantUML v. C4Version()
@enduml
